import themcontrols
import theminit


class Themhtml:
    def keylisthtml(self):
        retval='<datalist id="themkeys">'

        retval+=' <option value="{BACK}">'
        retval+=' <option value="{BACKSPACE}">'
        retval+=' <option value="{BKSP}">'
        retval+=' <option value="{BREAK}">'
        retval+=' <option value="{BS}">'
        retval+=' <option value="{CAP}">'
        retval+=' <option value="{CAPSLOCK}">'
        retval+=' <option value="{DEL}">'
        retval+=' <option value="{DELETE}">'
        retval+=' <option value="{DOWN}">'
        retval+=' <option value="{END}">'
        retval+=' <option value="{ENTER}">'
        retval+=' <option value="{ESC}">'
        retval+=' <option value="{F1}">'
        retval+=' <option value="{F10}">'
        retval+=' <option value="{F11}">'
        retval+=' <option value="{F12}">'
        retval+=' <option value="{F13}">'
        retval+=' <option value="{F14}">'
        retval+=' <option value="{F15}">'
        retval+=' <option value="{F16}">'
        retval+=' <option value="{F17}">'
        retval+=' <option value="{F18}">'
        retval+=' <option value="{F19}">'
        retval+=' <option value="{F2}">'
        retval+=' <option value="{F20}">'
        retval+=' <option value="{F21}">'
        retval+=' <option value="{F22}">'
        retval+=' <option value="{F23}">'
        retval+=' <option value="{F24}">'
        retval+=' <option value="{F3}">'
        retval+=' <option value="{F4}">'
        retval+=' <option value="{F5}">'
        retval+=' <option value="{F6}">'
        retval+=' <option value="{F7}">'
        retval+=' <option value="{F8}">'
        retval+=' <option value="{F9}">'
        retval+=' <option value="{HELP}">'
        retval+=' <option value="{HOME}">'
        retval+=' <option value="{INS}">'
        retval+=' <option value="{INSERT}">'
        retval+=' <option value="{LEFT}">'
        retval+=' <option value="{LWIN}">'
        retval+=' <option value="{NUMLOCK}">'
        retval+=' <option value="{PGDN}">'
        retval+=' <option value="{PGUP}">'
        retval+=' <option value="{PRTSC}">'
        retval+=' <option value="{RIGHT}">'
        retval+=' <option value="{RMENU}">'
        retval+=' <option value="{RWIN}">'
        retval+=' <option value="{SCROLLLOCK}">'
        retval+=' <option value="{SPACE}">'
        retval+=' <option value="{TAB}">'
        retval+=' <option value="{UP}">'
        retval+=' <option value="{VK_ACCEPT}">'
        retval+=' <option value="{VK_ADD}">'
        retval+=' <option value="{VK_APPS}">'
        retval+=' <option value="{VK_ATTN}">'
        retval+=' <option value="{VK_BACK}">'
        retval+=' <option value="{VK_CANCEL}">'
        retval+=' <option value="{VK_CAPITAL}">'
        retval+=' <option value="{VK_CLEAR}">'
        retval+=' <option value="{VK_CONTROL}">'
        retval+=' <option value="{VK_CONVERT}">'
        retval+=' <option value="{VK_CRSEL}">'
        retval+=' <option value="{VK_DECIMAL}">'
        retval+=' <option value="{VK_DELETE}">'
        retval+=' <option value="{VK_DIVIDE}">'
        retval+=' <option value="{VK_DOWN}">'
        retval+=' <option value="{VK_END}">'
        retval+=' <option value="{VK_EREOF}">'
        retval+=' <option value="{VK_ESCAPE}">'
        retval+=' <option value="{VK_EXECUTE}">'
        retval+=' <option value="{VK_EXSEL}">'
        retval+=' <option value="{VK_F1}">'
        retval+=' <option value="{VK_F10}">'
        retval+=' <option value="{VK_F11}">'
        retval+=' <option value="{VK_F12}">'
        retval+=' <option value="{VK_F13}">'
        retval+=' <option value="{VK_F14}">'
        retval+=' <option value="{VK_F15}">'
        retval+=' <option value="{VK_F16}">'
        retval+=' <option value="{VK_F17}">'
        retval+=' <option value="{VK_F18}">'
        retval+=' <option value="{VK_F19}">'
        retval+=' <option value="{VK_F2}">'
        retval+=' <option value="{VK_F20}">'
        retval+=' <option value="{VK_F21}">'
        retval+=' <option value="{VK_F22}">'
        retval+=' <option value="{VK_F23}">'
        retval+=' <option value="{VK_F24}">'
        retval+=' <option value="{VK_F3}">'
        retval+=' <option value="{VK_F4}">'
        retval+=' <option value="{VK_F5}">'
        retval+=' <option value="{VK_F6}">'
        retval+=' <option value="{VK_F7}">'
        retval+=' <option value="{VK_F8}">'
        retval+=' <option value="{VK_F9}">'
        retval+=' <option value="{VK_FINAL}">'
        retval+=' <option value="{VK_HANGEUL}">'
        retval+=' <option value="{VK_HANGUL}">'
        retval+=' <option value="{VK_HANJA}">'
        retval+=' <option value="{VK_HELP}">'
        retval+=' <option value="{VK_HOME}">'
        retval+=' <option value="{VK_INSERT}">'
        retval+=' <option value="{VK_JUNJA}">'
        retval+=' <option value="{VK_KANA}">'
        retval+=' <option value="{VK_KANJI}">'
        retval+=' <option value="{VK_LBUTTON}">'
        retval+=' <option value="{VK_LCONTROL}">'
        retval+=' <option value="{VK_LMENU}">'
        retval+=' <option value="{VK_LSHIFT}">'
        retval+=' <option value="{VK_LWIN}">'
        retval+=' <option value="{VK_MBUTTON}">'
        retval+=' <option value="{VK_MENU}">'
        retval+=' <option value="{VK_MODECHANGE}">'
        retval+=' <option value="{VK_MULTIPLY}">'
        retval+=' <option value="{VK_NEXT}">'
        retval+=' <option value="{VK_NONAME}">'
        retval+=' <option value="{VK_NONCONVERT}">'
        retval+=' <option value="{VK_NUMLOCK}">'
        retval+=' <option value="{VK_NUMPAD0}">'
        retval+=' <option value="{VK_NUMPAD1}">'
        retval+=' <option value="{VK_NUMPAD2}">'
        retval+=' <option value="{VK_NUMPAD3}">'
        retval+=' <option value="{VK_NUMPAD4}">'
        retval+=' <option value="{VK_NUMPAD5}">'
        retval+=' <option value="{VK_NUMPAD6}">'
        retval+=' <option value="{VK_NUMPAD7}">'
        retval+=' <option value="{VK_NUMPAD8}">'
        retval+=' <option value="{VK_NUMPAD9}">'
        retval+=' <option value="{VK_OEM_CLEAR}">'
        retval+=' <option value="{VK_PA1}">'
        retval+=' <option value="{VK_PAUSE}">'
        retval+=' <option value="{VK_PLAY}">'
        retval+=' <option value="{VK_PRINT}">'
        retval+=' <option value="{VK_PRIOR}">'
        retval+=' <option value="{VK_PROCESSKEY}">'
        retval+=' <option value="{VK_RBUTTON}">'
        retval+=' <option value="{VK_RCONTROL}">'
        retval+=' <option value="{VK_RETURN}">'
        retval+=' <option value="{VK_RIGHT}">'
        retval+=' <option value="{VK_RMENU}">'
        retval+=' <option value="{VK_RSHIFT}">'
        retval+=' <option value="{VK_RWIN}">'
        retval+=' <option value="{VK_SCROLL}">'
        retval+=' <option value="{VK_SELECT}">'
        retval+=' <option value="{VK_SEPARATOR}">'
        retval+=' <option value="{VK_SHIFT}">'
        retval+=' <option value="{VK_SNAPSHOT}">'
        retval+=' <option value="{VK_SPACE}">'
        retval+=' <option value="{VK_SUBTRACT}">'
        retval+=' <option value="{VK_TAB}">'
        retval+=' <option value="{VK_UP}">'
        retval+=' <option value="{ZOOM}">'
        retval+=' <option value="{VK_LEFT}">'

        retval+='</datalist>'
        return(retval)

    def defaultsettings(self):
        #set the default JavaScript Variables
        retval='<script>'
        #Don't declare it as var it get's hoisted out of scope
        retval+='forcecoords={0};\n'.format(themcontrols.ctrls.settings['forcecoords'])
        retval+='loadmode="{0}";\n'.format(themcontrols.ctrls.settings['loadmode'])
        retval+='autoexpand="{0}";\n'.format(themcontrols.ctrls.settings['autoexpand'])
        if themcontrols.ctrls.settings["tech"] != theminit.orgtech:
            retval+='redirect("")'
            theminit.orgtech = themcontrols.ctrls.settings["tech"]
        retval+='</script>\n'
        return(retval)
